In [15]:
import tensorflow as tf
from keras import models
from keras.models import Sequential
from keras.layers import Dense,Dropout, BatchNormalization
from keras import regularizers, layers
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import tensorflow_addons as tfa

original_df = pd.read_csv('datasets/WineQT.csv')
original_df = original_df.drop('Id',axis =1)
original_df.columns

# raw_val_ds = tf.keras.utils.text_dataset_from_directory(
#     'aclImdb/train', 
#     validation_split=0.2, 
#     subset='validation', 
#     seed=42)

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [16]:
original_df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5

In [17]:
wine_features = original_df.copy()
wine_labels = wine_features.pop('quality')
wine_features

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2

In [29]:
wine_model = tf.keras.Sequential([
  layers.Activation(activation='relu'),
  layers.Dense(64),
  layers.Dense(1),
])


wine_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.keras.optimizers.Adam())

In [30]:
wine_model.fit(wine_features, wine_labels, epochs=10)

Epoch 1/10
36/36 [==============================] - 0s 1ms/step - loss: 9.7341
Epoch 2/10
36/36 [==============================] - 0s 734us/step - loss: 0.7484
Epoch 3/10
36/36 [==============================] - 0s 730us/step - loss: 0.6636
Epoch 4/10
36/36 [==============================] - 0s 743us/step - loss: 0.6150
Epoch 5/10
36/36 [==============================] - 0s 743us/step - loss: 0.5899
Epoch 6/10
36/36 [==============================] - 0s 744us/step - loss: 0.5799
Epoch 7/10
36/36 [==============================] - 0s 729us/step - loss: 0.5669
Epoch 8/10
36/36 [==============================] - 0s 743us/step - loss: 0.5346
Epoch 9/10
36/36 [==============================] - 0s 743us/step - loss: 0.5090
Epoch 10/10
36/36 [==============================] - 0s 730us/step - loss: 0.5056

In [31]:
normalize = layers.Normalization()

In [32]:
normalize.adapt(wine_features)

In [41]:
norm_wine_model = tf.keras.Sequential([
  normalize,
  layers.Dense(32),
  layers.Dense(1)
])

norm_wine_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                        metrics=tf.metrics.BinaryAccuracy(threshold=0.0),
                           optimizer = tf.keras.optimizers.Adam())

norm_wine_model.fit(wine_features, wine_labels, epochs=10)

Epoch 1/10
36/36 [==============================] - 0s 917us/step - loss: 31.4588 - binary_accuracy: 0.0000e+00
Epoch 2/10
36/36 [==============================] - 0s 800us/step - loss: 27.7325 - binary_accuracy: 0.0000e+00
Epoch 3/10
36/36 [==============================] - 0s 771us/step - loss: 24.1502 - binary_accuracy: 0.0000e+00
Epoch 4/10
36/36 [==============================] - 0s 800us/step - loss: 20.2497 - binary_accuracy: 0.0000e+00
Epoch 5/10
36/36 [==============================] - 0s 829us/step - loss: 16.0389 - binary_accuracy: 0.0000e+00
Epoch 6/10
36/36 [==============================] - 0s 800us/step - loss: 11.8276 - binary_accuracy: 0.0000e+00
Epoch 7/10
36/36 [==============================] - 0s 843us/step - loss: 7.9653 - binary_accuracy: 0.0000e+00
Epoch 8/10
36/36 [==============================] - 0s 800us/step - loss: 4.8545 - binary_accuracy: 0.0000e+00
Epoch 9/10
36/36 [==============================] - 0s 829us/step - loss: 2.7100 - binary_accuracy: 0.0000e+00
Epoch 10/10
36/36 [==============================] - 0s 758us/step - loss: 1.4394 - binary_accuracy: 0.0000e+00

In [42]:
wine_features

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2

In [43]:
wine_model.summary()
predictions = wine_model.predict(wine_features)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 activation_2 (Activation)   (None, 11)                0

 dense_10 (Dense)            (None, 64)                768

 dense_11 (Dense)            (None, 1)                 65

=================================================================
Total params: 833 (3.25 KB)
Trainable params: 833 (3.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
36/36 [==============================] - 0s 757us/step

In [44]:
pred_label = np.argmax(predictions)
pred_label

462